export const DEFAULT_PAGE_WIDTH = 793.8;
export const DEFAULT_PAGE_HEIGHT = 1122;
export const DEFAULT_PAGE_PADDING = 20;
export const DEFAULT_PAGE_GAP = 20;
export const DEFAULT_DOCUMENT_FONT_FAMILY =
  '"Inter", "Helvetica Neue", Arial, sans-serif';
export const DEFAULT_DOCUMENT_FONT_SIZE = 16;
export const DEFAULT_DOCUMENT_LINE_HEIGHT = 1.6;
export const DEFAULT_DOCUMENT_LINE_HEIGHT_PX =
  DEFAULT_DOCUMENT_FONT_SIZE * DEFAULT_DOCUMENT_LINE_HEIGHT;
export const DEFAULT_DOCUMENT_FONT = `${DEFAULT_DOCUMENT_FONT_SIZE}px ${DEFAULT_DOCUMENT_FONT_FAMILY}`;
